import {
  CMS_USER_API,
  CONTENT_SERVICE_API,
  DISPLAY_SERVICE_API,
  EPIN_SERVICE_API,
  NOTIFICATION_SERVICE_API,
  PROFILE_SERVICE_API,
  PROMOCODE_SERVICE_API,
  SUBSCRIPTION_SERVICE_API,
} from "@/lib/config";

// cms service
const CMS_LOGIN = `${CMS_USER_API}/cmsservice/Users/Login`;
const CMS_USER = `${CMS_USER_API}/CmsUsers`;
const PASSWORD_RESET = `${CMS_USER_API}/cmsservice/Users/Update`;
const CMS_USER_CREATE = `${CMS_USER_API}/cmsservice/Users/Create`;
const CMS_ACCESS_ROLE = `${CMS_USER_API}/Roles`;
const CMS_ACCESS_LVL = `${CMS_USER_API}/AccessLevels`;

// disply service
const DISPLAY_AD_LIST = `${DISPLAY_SERVICE_API}/AdsList`;
const DISPLAY_AD_ITEMS = `${DISPLAY_SERVICE_API}/AdsItem`;
const DISPLAY_AD_STREAMING = `${DISPLAY_SERVICE_API}/AdsStreaming`;
const DISPLAY_AD_SLIDER_ITEMS = `${DISPLAY_SERVICE_API}/SliderItem`;
const DISPLAY_PLAYLISTS = `${DISPLAY_SERVICE_API}/Playlists`;
const DISPLAY_ADMINPLAYLISTTILES = `${DISPLAY_SERVICE_API}/AdminPlaylistTitle`;

// profile service
const PROFILE_PROFILE = `${PROFILE_SERVICE_API}/Profiles`;
const PROFILE_FAVOURITE = `${PROFILE_SERVICE_API}/Favourites`;
const PROFILE_USER_DEVICE = `${PROFILE_SERVICE_API}/UserDevices`;
const PROFILE_LIKE = `${PROFILE_SERVICE_API}/Likes`;
const PROFILE_DOWNLOD = `${PROFILE_SERVICE_API}/Downloads`;
const PROFILE_USER_SHARE = `${PROFILE_SERVICE_API}/UserShares`;

// Subscription service
const SUBSCRIPTION_GATEWAY_RAW_EVENTS = `${SUBSCRIPTION_SERVICE_API}/GatewayRawEvents`;
const SUBSCRIPTION_PAYMENT_GATEWAY = `${SUBSCRIPTION_SERVICE_API}/PaymentGateways`;
const SUBSCRIPTION_SUBSCRIPTION_PLAN = `${SUBSCRIPTION_SERVICE_API}/SubscriptionPlans`;
const SUBSCRIPTION_SUBSCRIPTION = `${SUBSCRIPTION_SERVICE_API}/Subscriptions`;
const SUBSCRIPTION_TRANSACTION = `${SUBSCRIPTION_SERVICE_API}/Transactions`;
const SUBSCRIPTION_CP_DETAIL = `${SUBSCRIPTION_SERVICE_API}/CpDetails`;

// Content Service
const CONTENT_TITLE = `${CONTENT_SERVICE_API}/titles`;
const CONTENT_GENRE = `${CONTENT_SERVICE_API}/Genres`;
const CONTENT_TAG = `${CONTENT_SERVICE_API}/Tags`;
const CONTENT_CREDIT = `${CONTENT_SERVICE_API}/Credits`;
const CONTENT_EPISODE = `${CONTENT_SERVICE_API}/Episodes`;
const CONTENT_ROLES = `${CONTENT_SERVICE_API}/Roles`;
const CONTENT_TRAILERS = `${CONTENT_SERVICE_API}/Trailers`;
const CONTENT_SERIES = `${CONTENT_SERVICE_API}/titles?$expand=Series(expand=Seasons(expand=Episodes))`;
const CONTENT_SEASONS = `${CONTENT_SERVICE_API}/Seasons`;
const CONTENT_MOVIE = `${CONTENT_SERVICE_API}/titles?$expand=Movie`;
const CREDIT_ROLES = `${CONTENT_SERVICE_API}/creditRole`;
const GENRE_TITLES = `${CONTENT_SERVICE_API}/genreTitle`;
const TAG_TITLES = `${CONTENT_SERVICE_API}/tagTitle`;
const CREDIT_TITLES = `${CONTENT_SERVICE_API}/titleCredit`;

const FAQ_TITLES = `${CMS_USER_API}/Faqtitles`;
const FAQs_FAQs = `${CMS_USER_API}/FAQs`;
const TOTAL_COUNT = `${CMS_USER_API}/TotalCounts`;

const TERMS_AND_CONDITIONS = `${CMS_USER_API}/termsandconditions`
const PRIVACY_AND_POLICIES =  `${CMS_USER_API}/privacyandpolicies`
//Prmocode Service
const PROMOCODE_PROMOCODE = `${PROMOCODE_SERVICE_API}/PromoCodes`;
const PROMOCODE_PROMOCODE_USER = `${PROMOCODE_SERVICE_API}/PromoCodeUsers`;

const EPIN_EPIN = `${EPIN_SERVICE_API}/Epins`;
const EPIN_EPIN_USER = `${EPIN_SERVICE_API}/EpinUsers`;
const EPIN_EPIN_GENERATION_JOB = `${EPIN_SERVICE_API}/EpinGenerationJobs`;
const EPIN_GENERATION_JOB = `${EPIN_SERVICE_API}/GenerateEpin/generatejob`;
const EPIN_EPIN_PACKAGE = `${EPIN_SERVICE_API}/EpinPackages`;
const EPIN_ACTIVATE = `${EPIN_SERVICE_API}/Activate/activate`;

const NOTIFICATION_NOTI = `${NOTIFICATION_SERVICE_API}/Notification`;
const NOTIFICATION_TOPIC = `${NOTIFICATION_SERVICE_API}/Topic`;
export {
  CMS_LOGIN,
  CMS_USER,
  CMS_USER_CREATE,
  CMS_ACCESS_ROLE,
  CMS_ACCESS_LVL,
  PASSWORD_RESET,
  //
  DISPLAY_AD_LIST,
  DISPLAY_AD_ITEMS,
  DISPLAY_AD_STREAMING,
  DISPLAY_AD_SLIDER_ITEMS,
  DISPLAY_PLAYLISTS,
  DISPLAY_ADMINPLAYLISTTILES,
  //
  PROFILE_PROFILE,
  PROFILE_FAVOURITE,
  PROFILE_USER_DEVICE,
  PROFILE_LIKE,
  PROFILE_DOWNLOD,
  PROFILE_USER_SHARE,
  SUBSCRIPTION_GATEWAY_RAW_EVENTS,
  SUBSCRIPTION_PAYMENT_GATEWAY,
  SUBSCRIPTION_SUBSCRIPTION_PLAN,
  SUBSCRIPTION_SUBSCRIPTION,
  SUBSCRIPTION_CP_DETAIL,
  SUBSCRIPTION_TRANSACTION,
  CONTENT_TITLE,
  CONTENT_GENRE,
  CONTENT_TAG,
  CONTENT_TRAILERS,
  PROMOCODE_PROMOCODE,
  PROMOCODE_PROMOCODE_USER,
  CONTENT_EPISODE,
  CONTENT_ROLES,
  CONTENT_CREDIT,
  CONTENT_SERIES,
  CONTENT_SEASONS,
  CONTENT_MOVIE,
  EPIN_EPIN,
  EPIN_EPIN_USER,
  EPIN_EPIN_GENERATION_JOB,
  EPIN_GENERATION_JOB,
  EPIN_EPIN_PACKAGE,
  EPIN_ACTIVATE,
  CREDIT_ROLES,
  GENRE_TITLES,
  TAG_TITLES,
  NOTIFICATION_NOTI,
  NOTIFICATION_TOPIC,
  CREDIT_TITLES,
  FAQ_TITLES,
  FAQs_FAQs,
  TOTAL_COUNT,
  //
  TERMS_AND_CONDITIONS,
  PRIVACY_AND_POLICIES
};
